name: high_q_notifications
description:
  A Flutter package that handles push notifications efficiently using Firebase Messaging and
  local notifications. Supports background message handling, scheduling notifications,
  and offers utilities for timezone management and dependency injection.


version: 1.0.2
homepage: https://github.com/azabcodes/high_q_notifications

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  dio: ^5.8.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  timezone: ^0.10.1
  args: ^2.7.0

executables:
  cli: cli.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
