name: high_q_notifications
description:
  A Flutter package that handles push notifications efficiently using Firebase Messaging and
  local notifications. Supports background message handling, scheduling notifications,
  and offers utilities for timezone management and dependency injection.


version: 2.0.3
homepage: https://github.com/azabcodes/high_q_notifications
issue_tracker: https://github.com/azabcodes/high_q_notifications/issues

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.4.2
  dio: ^5.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  dartz: ^0.10.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  timezone: ^0.10.1

executables:
  high_q_notifications: setup_notifications




topics:
  - notifications
  - push-notifications
  - flutter-notifications
  - firebase-messaging
  - high-q-notifications



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
