// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaBup6uHeLN1zGhUimQdPpjmy9NKiyLKU',
    appId: '1:679813817978:web:0a34722ff615e8cebb7dc3',
    messagingSenderId: '679813817978',
    projectId: 'notification-example-highq',
    authDomain: 'notification-example-highq.firebaseapp.com',
    storageBucket: 'notification-example-highq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjR2uNRfgeF7CC5CdhMjQIswf9yeTxdXI',
    appId: '1:679813817978:android:6251944fd4ab297abb7dc3',
    messagingSenderId: '679813817978',
    projectId: 'notification-example-highq',
    storageBucket: 'notification-example-highq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJo17tcytsqAGkyBNBcrfmxzBhvYYd04w',
    appId: '1:679813817978:ios:5dd435b8024130cabb7dc3',
    messagingSenderId: '679813817978',
    projectId: 'notification-example-highq',
    storageBucket: 'notification-example-highq.firebasestorage.app',
    iosBundleId: 'com.highq.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJo17tcytsqAGkyBNBcrfmxzBhvYYd04w',
    appId: '1:679813817978:ios:5dd435b8024130cabb7dc3',
    messagingSenderId: '679813817978',
    projectId: 'notification-example-highq',
    storageBucket: 'notification-example-highq.firebasestorage.app',
    iosBundleId: 'com.highq.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaBup6uHeLN1zGhUimQdPpjmy9NKiyLKU',
    appId: '1:679813817978:web:e126789aa19b3e3cbb7dc3',
    messagingSenderId: '679813817978',
    projectId: 'notification-example-highq',
    authDomain: 'notification-example-highq.firebaseapp.com',
    storageBucket: 'notification-example-highq.firebasestorage.app',
  );
}
